### ISSUE TITLE
There may be some possible mistakes of the code

### ISSUE THREAD

**Issue by 222huan** [hectornieto/pypro4sail#2]
Hello!
I think there may be some possible mistakes of the code in the 4SAIL TIR simulations. The changes I have made can be found in https://github.com/222huan/py4SAIL
After modifying the code, I have compared the simulation results with the figures display in some papers, and the result is consistent.

**Comment by hectornieto** [comment]
I would say that the code is OK, but in any case it will be much easier/efficient if you suggested a pull request instead of commenting the changes in your own README.md files:
```
In pypro4sail\four_sail.py:

the function calc_lidf_verhoef calculated LIDF with 18 angles, while there are 13 angles used in FORTRAN code

the function weighted_sum_over_lidf also use 18 angles, while there are 13 angles used in FORTRAN code

This may not be a mistake but another parameterization scheme, but I have changed it to keep with the FORTRAN code
```
The fact that we are using 18 angle steps should not affect to the output, as these steps are just used to integrate along the hemisphere. 18 steps vs. 13 would indeed provide a more detailed integration, with the disadvantage that it would be less efficient (a loop of 18 steps instead of 13). In a similar manner other 4sail repos also use 18 angle steps, e.g.
[jgomezdans](https://github.com/jgomezdans/prosail/blob/8d3d7e9ab04c33ea41bddb0c7f2721865ce8f01a/prosail/FourSAIL.py#L226)

```
In pypro4sail\four_sail.py line 437:

rsodt = ((tss + tsd) * tdo + (tsd + tss * rsoil * rdd) * too) * rsoil / dn

should be changed as:

rsodt = ((tss + tsd) * tdo + (tsd + tss * rsoil * rdd) * too) * rsoil / dn + rsod
```
Indeed the `rsod` factor you add in that line is added before in our code and other similar code at line [426](https://github.com/hectornieto/pypro4sail/blob/f1a0ce2e9ea7be2aea67b2e653ce6feb44aaeddf/pypro4sail/four_sail.py#L426). Indeed you are double accounting `rsod`, as you are adding it again at your line [469](https://github.com/222huan/py4SAIL/blob/f7796d89e53c2df3b296b8aebf713617493e3740/four_sail.py#L469), (see back to your line [457](https://github.com/222huan/py4SAIL/blob/f7796d89e53c2df3b296b8aebf713617493e3740/four_sail.py#L457)). If you want to keep consistency with the outputs, take a look at the code by [jbferet](https://gitlab.com/jbferet/prosail/-/blob/master/R/Lib_PROSAIL.R#L444)

In any case, the structure of our equations is in agreement with the first term of Eq. (11) in [Verhoef et al. 2007](https://doi.org/10.1109/TGRS.2007.895844):

![image](https://user-images.githubusercontent.com/7302862/192331385-72182e95-162b-4b22-9db9-aed838ae8aa3.png)

```
In pypro4sail\pypro4sail.py line 226:

tso = tss * too + tss * (tdo + rsoil * rdd * too) / (1. - rsoil * rdd)

should be changed as:

tso = tsstoo + tss * (tdo + rsoil * rdd * too) / (1. - rsoil * rdd)
```
`tsstoo`, the bidirectional transmittance, is the product of `tss*too` so both lines are equivalent

**Comment by 222huan** [comment]
Thanks for your reply!

- As for the choice of angles, I understand it was just another more effective way, and I have mentioned that "_This may not be a mistake but another parameterization scheme_".

- As for **rsodt plus rsod**, it is my fault and thanks for pointing this out.

- As for tsstoo, it is calculated via the function hotspot_calculations line [1197](https://github.com/hectornieto/pypro4sail/blob/f1a0ce2e9ea7be2aea67b2e653ce6feb44aaeddf/pypro4sail/four_sail.py#L1197). I have checked the values of tsstoo and tss\*too, and found there are differences between them. Finally, I have respectively used tsstoo and tss\*too to check the results, and compared the results with those in Fig. 5 of [Verhoef et al. 2007](https://doi.org/10.1109/TGRS.2007.895844). Only when using tsstoo instead of tss\*too, the directional brightness temperature in the solar principle plane agrees with the results displayed in [Verhoef et al. 2007](https://doi.org/10.1109/TGRS.2007.895844). The validation results are shown in [validation.ipynb](https://github.com/222huan/py4SAIL/blob/main/validation.ipynb).

**Comment by hectornieto** [comment]
OK, regarding tss*too you are right, I have updated the code and credited your contribution,

Thanks!
